export default {
	Afrikaans: "Bergingtoestemmings ontbreek.",
	Arabic: "أذونات التخزين مفقودة.",
	Basque: "Biltegiratze-baimenak falta dira.",
	Belarusian: "Адсутнічаюць дазволы на захоўванне.",
	Bulgarian: "Липсват разрешения за съхранение.",
	Catalan: "Falten permisos d'emmagatzematge.",
	Chinese: "缺少存儲權限。",
	Czech: "Chybí oprávnění úložiště.",
	Danish: "Manglende lagertilladelser.",
	Dutch: "Ontbrekende opslagrechten.",
	English: "Missing storage permissions.",
	Estonian: "Puuduvad salvestusõigused.",
	Faroese: "Missing storage permissions.",
	Finnish: "Tallennusoikeudet puuttuvat.",
	French: "Autorisations de stockage manquantes.",
	German: "Fehlende Speicherberechtigungen.",
	Greek: "Λείπουν δικαιώματα αποθήκευσης.",
	Hebrew: "חסרות הרשאות אחסון.",
	Icelandic: "Vantar geymsluheimildir.",
	Indonesian: "Izin penyimpanan tidak ada.",
	Italian: "Autorizzazioni di archiviazione mancanti.",
	Japanese: "ストレージ権限がありません。",
	Korean: "저장소 권한이 없습니다.",
	Latvian: "Trūkst krātuves atļauju.",
	Lithuanian: "Trūksta saugyklos leidimų.",
	Norwegian: "Mangler lagringstillatelser.",
	Polish: "Brak uprawnień do przechowywania.",
	Portuguese: "Permissões de armazenamento ausentes.",
	Romanian: "Lipsesc permisiuni de stocare.",
	Russian: "Отсутствуют разрешения на хранение.",
	SerboCroatian: "Недостају дозволе за складиштење.",
	Slovak: "Chýbajúce povolenia na ukladací priestor.",
	Slovenian: "Manjkajoča dovoljenja za shranjevanje.",
	Spanish: "Faltan permisos de almacenamiento.",
	Swedish: "Lagringsbehörigheter saknas.",
	Thai: "ไม่มีสิทธิ์ในการจัดเก็บข้อมูล",
	Turkish: "Eksik depolama izinleri.",
	Ukrainian: "Відсутні дозволи на зберігання.",
	Vietnamese: "Thiếu quyền lưu trữ.",
	ChineseSimplified: "缺少存储权限。",
	ChineseTraditional: "缺少存儲權限。",
	Unknown: "Missing storage permissions.",
	Hungarian: "Hiányzó tárolási engedélyek.",
}