name: Build
on: workflow_dispatch
jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install prerequisites
        run: sudo apt install apktool && pip3 install objection
      - name: Create workspace
        run: mkdir apk
      - name: Get version
        id: version
        uses: ExternalAddress4401/get-version@v1.1
      - name: Check cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/apk
          key: ${{ runner.os }}-node-${{ steps.version.outputs.version }}
      - name: Stop if cache hit
        if: steps.cache.outputs.cache-hit == 'true'
        run: echo "Cache hit. No new version available." #&& exit 0
      - name: Download APK
        if: steps.cache.outputs.cache-hit != 'true'
        uses: ExternalAddress4401/download-apk-action@v1.1
        with:
          version: ${{ steps.version.outputs.version }}
          data-url: ${{ steps.version.outputs.data-url}}
      - name: Extract APK
        run: apktool d beatstar.apk --only-main-classes
      - name: Modify APK
        uses: ExternalAddress4401/edit-apk-action@v1.1
      - name: Print
        run: cd apk/beatstar/dist && ls
      - name: Move APK
        run: mv apk/beatstar/dist/beatstar.apk ../../../
