name: Build
on: workflow_dispatch
jobs:
  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install prerequisites
        run: sudo apt install apktool && pip3 install objection
      - name: Get version
        id: version
        uses: ExternalAddress4401/get-version@v1.1
      - name: Download APK
        uses: ExternalAddress4401/download-apk-action@v1.1
        with:
          version: ${{ steps.version.outputs.version }}
          data-url: ${{ steps.version.outputs.data-url }}
      - name: Extract APK
        run: apktool d beatstar.apk --only-main-classes
      - name: Modify APK
        uses: ExternalAddress4401/edit-apk-action@v1.1
      - name: Build APK
        run: apktool b beatstar
      - name: Move APK
        run: rm ~/beatstar.apk && mv ~/beatstar/dist/beatstar.apk ~/
